### PR TITLE
Update supported versions in release notes

### PR DESCRIPTION
**Pull request by mikehardy**

### CODE REVIEW

**Comment by quachsimon** [comment]
Much clearer! Can update now knowing the latest SDKs are supported.

**Comment by mikehardy** [comment]
If anyone from `@invertase` wants to take a look for review then, this seems to be better wording :-)

**Comment by mikehardy** [comment]
@Salakar I'd like to get this merged if possible and then use it as a base for future updates

There will be trouble as it appears they packaged MLKit breaking changes into ios pods 6.10 along with iOS13 crash fixes.

**Comment by CaptainJeff** [comment]
@mikehardy 

I'm not sure I understand your point. When were the MLKit breaking changes introduced? In 6.10? And your PR is updating the documentation to use version 6.8.1 instead of 6.2?

Or am I misreading the versioning?

**Comment by mikehardy** [comment]
@CaptainJeff my note was fairly cryptic

I push these updates out periodically and they are always outdated a week after I attempt, so I may be recommending 6.8.1 in this time capsule of a PR but now for v5 I would recommend 6.10

However, v5 doesn't use MLKit which is important. v6 uses MLKit and if you use the pod version 6.10 of firebase ios sdk now you will get MLKit breaking changes which may not be what you want. So any doc updates for v6 should take that in to consideration as RNFBv6 MLKit API coverage may break as you cross from 6.9 to 6.10

This will all likely be even more out of date next week

**Comment by CaptainJeff** [comment]
@mikehardy 

Understood! Thanks for your explanation.

If we don't use MLKit these breaking changes won't be an issue, correct? And 6.10 would be the preferred version

**Comment by mikehardy** [comment]
@CaptainJeff if you use v5, you can and should use most current. I use v5 and I am on 6.10. No problems. If you use v6 I can't assert anything about compatibility past 6.9.x. You'd have to try it. But if it were me and I was on v6 and it compiles *and* and I was not using MLKit functionality, I'd go with it.

**Comment by CaptainJeff** [comment]
@mikehardy great. Thanks for your help. I'll report back if there are any issues with 6.10

**Pull request closed without merging**
