### PR TITLE
docs: Update User.UserMetadata timestamp formats to match plugin return vals

### PR DESCRIPTION
**Pull request by mikehardy**
For the 5.x Auth version now, I noticed the User.UserMetadata times were coming back as standard Date milliseconds values, and thought the documentation should match

### CODE REVIEW

**Comment by Salakar** [comment]
Going to put this one on hold for v6, if the official firebase docs state that these return a UTC string then we should probably update the [v6 implementation](https://github.com/invertase/react-native-firebase/tree/master/packages/auth) to match this, otherwise it's a not compatible with the Firebase Web SDK

**Comment by Salakar** [comment]
Not sure if you want to do anything for this one in v5 @mikehardy, will leave it up to you :upside_down_face: , maybe the docs could be updated but also a note added saying that this is likely to change in v6 as it's currently incorrect and should be returning a UTC string to match the Web SDK

**Comment by mikehardy** [comment]
Hmm - I prefer documentation that matches implementation at all times if possible, so I re-worked the wording to clearly indicate it was going to change, but also to let people know what it is now. What do you think @Salakar ?

**Comment by Salakar** [comment]
LGTM

**Pull request merged**
