### PR TITLE
Prepare for 5.4.3 release

### PR DESCRIPTION
**Pull request by mikehardy**
Sorry for being change-y on the whitespace in this file, I delinted it at the same time. If you look at it with no whitespace it's clean.

This is I think the full list of changes merged in since 5.4.2, formatted I hope correctly, and I hope easy and ready to go

I think everything is in shape for a 5.4.3 release after the breaking change notice on npm install is approved-by-not-me-the-author and merged-by-anyone: https://github.com/invertase/react-native-firebase/pull/2214

### CODE REVIEW

**Comment by mikehardy** [comment]
I accidentally did something wrong (an extra space around the triple-backtick) in my last commit here and need to fix it, while formalizing the 5.4.3 release.

I am also cleaning up my notification box, I didn't realize how multiple `>` would translate - they look bad and the notification needs to be one string next to one `>`

**Comment by mikehardy** [comment]
@Salakar I think the release notes are ready for merge assuming 5.4.3 is ready to go (it needs some release process work but is otherwise good to go I think?)

**Comment by Salakar** [comment]
Go go go =]

**Comment by mikehardy** [comment]
couldn't figure crashlytics out but reverting it clears android e2e so I reverted, and I removed it from changelog here to match which means re-approval. Now the release is clean on both platforms

**Pull request merged**
