### PR TITLE
Added in-app-messaging directory with android.md and ios.md

### PR DESCRIPTION
**Pull request by HessiPard**
The main doc for [v5](https://rnfirebase.io/docs/v5.x.x/getting-started) doesn't cover in-app-messaging module.
Based on my implemantations, [#1431](https://github.com/invertase/react-native-firebase/issues/1431) and [Official Guide](https://firebase.google.com/docs/in-app-messaging/get-started?platform=android), I added related files and hope it could help others.

### CODE REVIEW

**Comment by mikehardy** [comment]
@HessiPard that's a great start and should avoid confusion in the future for people wondering if it is possible - do you have any thing you could add in a getting-started maybe that indicates how to use it? Or simply (since I might be confused) pointing to the google firebase guides on the subject saying that it works as is with react-native-firebase and you just use the official APIs?

**Comment by HessiPard** [comment]
Ok.
I think the best description was given in this [tweet](https://twitter.com/mikediarmid/status/1032673313418616833) by @Salakar.
I will create a getting-started file with some notes and feel free to make any changes on my notes.

**Comment by mikehardy** [comment]
Sorry! I switched the branch to v5.x.x because that's what the docs site for v5 is built from, and it made quite a has of things for the moment, but it looks like you're patching it up - I'll wait for bit

**Comment by HessiPard** [comment]
Fine. Good Luck ✌

**Comment by HessiPard** [comment]
Ready To GO

**Comment by mikehardy** [comment]
had not scanned the docs PR queue in quite some time, sorry for letting this go to sleep. It just went live though! Thanks again for the help @HessiPard

**Pull request merged**
