### PR TITLE
Invites android doc update

### PR DESCRIPTION
**Pull request by trackq**

### CODE REVIEW

**Comment by Salakar** [comment]
@trackq I guess you meant to make this change for the 4.2.x branch - can you submit your PR to merge into 4.2.x branch not master, thanks

**Comment by Ehesp** [comment]
@trackq we're happy to link away to a hosted site such as medium. Would be good to share the post here though so we can give it a once over!

**Comment by trackq** [comment]
@Ehesp like so good enough?

**Comment by Salakar** [comment]
@trackq that's good thank you for this!

**Pull request merged**
