### PR TITLE
Update receiving-notifications.md

### PR DESCRIPTION
**Pull request by david-arteaga**
For the current latest version (5.x) of RN Firebase, calling `requestPermission` also calls the `registerForRemoteNotifications` method. This is required for the fcm token retrieved to be associated to a valid APNS token, and for push notifications to be delivered correctly to the device. (https://github.com/invertase/react-native-firebase/issues/1203#issuecomment-480549091)

I have been debugging an issue with push notifications and consistently calling the `requestPermission` method even when the user already granted permissions was the only fix.
There is also a `firebase.messaging().ios.registerForRemoteNotifications()` method available, but I found that when I called it from the JS thread, a warning popped up in Xcode saying that this method (the underlying `[RCTSharedApplication() registerForRemoteNotifications]` call) should only be made from the main thread.

This does not prompt the user on iOS after the first time the user responds to the dialog, so the user experience is not hurt by running this code over and over.

### CODE REVIEW

**Comment by mikehardy** [comment]
I think this is correct but I honestly have no idea how anyone could functionally use the v4.x branch anymore. I am aware of multiple SDK bugs with android SDK 28+ and iOS 13+ that aren't fixed until version numbers of the SDK high enough that you must use the v5.x branch in order to access them, and the play store and app store either won't accept apps targeted lower than android 28 or warn about ios < 13 compatibility with threats to reject. I think it's a dead branch

**Comment by mikehardy** [comment]
Maybe the fix is actually to wipe the v4.x docs and put a notice that it effectively can't be used owing to what I mentioned above

**Comment by david-arteaga** [comment]
Yes I agree with that, and it would the simplest solution.
Don’t know how many people are still using the v4 branch at the moment though.

**Comment by mikehardy** [comment]
hopefully zero ;-) (not being glib, it just really is non-deployable at this point)

**Comment by mikehardy** [comment]
I attempted to change the base to v5.x.x because I thought it might be useful there still but it did not work out - if you still believe this is a useful change please feel free to add a note on a v5.x.x branch doc indicating requestPermission is basically required to call at all times. Might add that react-native-permissions is a great way to handle the permissions request in general as iOS13 is pretty picky about how it works, and that module is fully up to date and well supported.

**Pull request closed without merging**
